import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Header from "@/components/default/header/header";
import Footer from "@/components/default/footer/footer";
import "../lib/css/lib.scss";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Vels",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        /*<ThemeProvider theme={theme}>*/
            <html lang="en">
                <body className={inter.className}>
                    <div className="page-wrapper min-h-screen flex flex-col justify-between">
                        <Header></Header>
                            <main className="items-center p-24">
                                {children}
                            </main>
                        <Footer></Footer>
                    </div>
                </body>
            </html>
        /*</ThemeProvider>*/
    );
}
